# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-15 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
