# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_bookmark_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
